apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cicd-webdemo-0.1.{{ build.number }}
  labels:
    cicd-webdemo: cicd-webdemo
    version: webdemo-0.1.{{ build.number }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        cicd-webdemo: cicd-webdemo
        version: webdemo-0.1.{{ build.number }}
    spec:
      containers:
      - name: cicd-webdemo
        image: 10.25.0.141:5000/library/webdemo:0.1.{{ build.number }}
        ports:
        - containerPort: 8080
